SVG_NAMESPACE = "{http://www.w3.org/2000/svg}"
DEFAULT_TEXT_COLOR = "#000000"
XML_TYPE_1 = "Type1"
XML_TYPE_2 = "Type2"

HIGHLIGHT_COLOR_ACTIVE = "turquoise"
HIGHLIGHT_COLOR_REMEMBERED = "#AFEEEE"
HIGHLIGHT_COLOR_HINTS = "orange"
HIGHLIGHT_COLOR_OUTLINE = "red"
FILE_TYPES = [("SVG files", "*.svg"), ("Text files", "*.txt")]
DEFAULT_WINDOW_SIZE = "1280x720"
DEFAULT_SCALE_FACTOR = 1.1
DEFAULT_SCALE = 1.0
MAX_SCALE_DIMENSION = 10000

APP_TITLE = "UML Diagram Viewer"
APP_EXIT_MESSAGE = "Application is exiting..."
CANVAS_BG = "white"
TITLE_FONT = ("Helvetica", 10, "bold")
LABEL_FONT = ("Helvetica", 10)
SCROLLBAR_BG = "gray"
TRANSITION_TRACE_TITLE_BG = "lightgray"
TRANSITION_TRACE_BG = "#f0f0f0"
TRANSITION_TRACE_FG = "black"

RADIO_BUTTON_FONT = ("Verdana", 9)
